service: dynamoAndLambdaDemo

plugins:
  - serverless-plugin-typescript

provider: 
  name: aws
  runtime: nodejs12.x
  deploymentPrefix: demo-serverless
  stage: ${opt:stage} # prefer making stage explicit
  region: ap-southeast-2

  environment:
    STAGE: ${self:provider.stage}
    USERS_TABLE: ${self:service}-${self:provider.stage}-users

  iamRoleStatements:
    - Effect: "Allow"
      Action: "dynamodb:*"  
      Resource: "*"

functions:
  createUser: 
    handler: src/index.createUser
    description: Create 1 or more users
    events:
      - http:
          path: users
          method: post
  getUser: 
    handler: src/index.getUser
    description: List users
    events: 
      - http: 
          path: users/{id}
          method: get

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.USERS_TABLE}
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    
